apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::993865477170:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::993865477170:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1MA3N8EUVSAP4
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-27T17:19:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "859"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: da625d5e-82d1-4b23-9c57-c225e7e9b38f
